cargo-features = ["edition2024"]

[package]
name = "diagnostic"
version = "0.1.0"
edition = "2024"

[dependencies]
playdate-sys = { git = "https://github.com/boozook/playdate", rev = "66da849", optional = true }

[features]
std = []
pd = ["dep:playdate-sys"]

