cargo-features = ["edition2024"]

[package]
name = "diagnostic"
version = "0.1.0"
edition = "2024"

[dependencies]
playdate-sys = { version = "0.5.5", optional = true }

[features]
std = []
pd = ["dep:playdate-sys"]

